name: marekat

description: This is the flutter mobile application.

version: 1.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: any
  intl: any
  provider: any
  connectivity: any
  shimmer: any
  flutter_html: any
  flutter_svg: any
  url_launcher: any
  shared_preferences: any
  flutter_icons: any
  webview_flutter: ^2.3.1
  google_fonts: any
  flutter_rating_bar: any
  expandable: any
  dropdown_search: any
  flutter_countdown_timer: any
  intl_phone_number_input: any
  cupertino_icons: any
  carousel_slider: any
  timeline_tile: any
  shared_value: any
  permission_handler: ^6.0.0
  fluttertoast: ^8.0.7
  share: ^2.0.4
  path_provider: any
  path: any
  file_picker: ^3.0.3
  flutter_offline: any
  location: ^4.3.0
  flutter_phoenix: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.6
  json_serializable: ^3.3.0

flutter_launcher_name:
  name: "Daemmart"

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_intl:
  enabled: true
